; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor and upload configuration
monitor_port = /dev/cu.SLAB_USBtoUART
monitor_speed = 115200
upload_port = /dev/cu.SLAB_USBtoUART

build_flags = ;-D LOG_FRAMEWEB_ENABLED ; Enable debug output for FrameWeb (prefix [F])

; HTML-to-C++ generator
extra_scripts = pre:.pio/libdeps/esp32dev/Esp32_Framework/extra_script.py
custom_in_html = .pio/libdeps/esp32dev/Esp32_Framework/src/FrameWeb.html
								  src/eau.html
custom_out_h = .pio/libdeps/esp32dev/Esp32_Framework/src/FrameWeb.cpp
								include/eau.h
custom_out_zip = plain ; no zip because eau.h must remain readable

lib_deps = 
  https://github.com/tzapu/WiFiManager.git#master
  https://github.com/Links2004/arduinoWebSockets#master
  DNSServer
  WebServer
  ArduinoJson
	U8g2
	https://github.com/dupuyb/Esp32_Framework.git

[platformio]
description = Domotique Jeedom (water counter survey)
